apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titanic-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: titanic.local
      http:
        paths:
          Path: /
          pathType: Prefix
          backend:
            service:
              name: titanic-api-service
              port:
                number: 80